#8.15.21, 9.16.21, 6.11.23,  4.19.26, and 7.31.26
search_dir = "./"
title = "recordings"
#
import os
import datetime
from mutagen.mp4 import MP4
def pretty(length):
    secs = length
    mins = 0
    hrs = 0
    if secs > 59:
        while secs > 59:
            mins = mins + 1
            secs = secs - 60
    if mins >= 59:
        while mins > 59:
            hrs = hrs + 1
            mins = mins - 60
    if hrs == 0:
        hrs = ""
    else:
        hrs = str(hrs) + ":"
    secs = int(secs)
    secs = str(secs)
    mins = str(mins)
    if len(mins) == 1 and len(hrs) > 0:
        mins = "0" + mins
    if len(secs) == 1:
        secs = "0" + secs
    length = hrs + mins + ":" + secs
    return length
notes = os.listdir(search_dir)
badNames=[".DS_Store"]
for i in notes:
    if i in badNames:
        notes.remove(i)
for x in range(0, len(notes)):
    if not notes[x].endswith(".m4a"):
        notes[x] = ""
while "" in notes:
    notes.remove("") #!!
names = []
dates = []
times = []
sizes = []
isodates = []
pretable = """<!DOCTYPE html>
<!--Generated by sorting-recordings (https://github.com/jmoll1125/sorting-recordings/)-->
<html>
<head>
<title>"""+title+"""</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
td { padding: 0px; padding-right: 5px; border-bottom: 15px;}
a { text-decoration: none; }
a:visited{color:blue}
.red {color: rgb(199, 97, 90); }
thead {display: none;}
.hidden {display: none;}
</style>
<script src="sorttable.js"></script>
<script>
function sort(id) {
var myTH = document.getElementsByTagName("th")[id];
sorttable.innerSortFunction.apply(myTH, []);
};
</script>
</head>
<body>
<h1>"""+title+"""</h1>
<p>sort by: <a href="#" onclick="sort(1)">date</a> &nbsp; <a href="#" onclick="sort(2)">time</a> &nbsp; <a href="#" onclick="sort(3)">length</a>
<table id="notes" class="sortable">
<thead><tr><th>date</th><th>name</th><th>time</th><th>size</th></thead>
<tbody>
"""
posttable = """
</tbody>
</table>

</body>
</html>
"""
html = ""
for x in range (0, len(notes)):
    dispname = notes[x][:15]
    date = datetime.datetime.strptime(dispname, "%Y%m%d %H%M%S")
    dispname = date.strftime("%-m.%-d.%y %l:%M:%S %-p")
    length = MP4(search_dir+notes[x]).info.length
    dlength = pretty(length)
    dates.append(date.strftime("%Y%m%d%H%M%S"))
    times.append(date.strftime("%H%M%S"))
    names.append(dispname)
    html = html + "<tr><td><a href=\"" + search_dir + notes[x] +"\">" + names[x] +"</a> ("+dlength+") </td><td class=\"hidden\">" + dates[x] + "</td><td class=\"hidden\">" + times[x] + "</td><td class=\"hidden\">" + str(length) + "</td></tr>\r\n"
filename = datetime.datetime.now()
filename = filename.strftime("%Y%m%d%H%M")
filename = "sorting-recordings-" + filename + ".html"
f = open(filename, "w")
f.write(pretable)
f.write(html)
f.write(posttable)
f.close()
